### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Erkigmo** [RedRafe/pyse-changes#1]
When loading this without Py, it breaks
![image](https://github.com/RedRafe/pyse-changes/assets/122825731/696efdd1-2303-4c1a-9ef4-5862e849b41b)

**Comment by RedRafe** [comment]
Yes, it's possible that the ad-hoc SpaceEx doesn't work outside PySpEx. Maybe I'll refactor the code better to have a conditional opt for that
